version: 2.1

orbs:
  python: circleci/python@1.3.2

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          command: flake8
          name: Lint
      - run:
          command: mypy algorithms
          name: Type hinting
      - run:
          command: pytest
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
